<?php

//Display errors for debugging

// ini_set('display_errors', 1);
// ini_set('display_startup_errors', 1);
// error_reporting(E_ALL);



// Auto load generated by composer
require 'vendor/autoload.php';

use Aws\S3\S3Client; 

//load .env file
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();



// Connection to the database
// host, admin, password, db name, port
$con = mysqli_connect($_ENV['DB_HOST'], $_ENV['DB_USER'], $_ENV['DB_PASSWORD'], $_ENV['DB_NAME'], $_ENV['DB_PORT']);

//check connection
if (mysqli_connect_errno()){
    die("Connection failed: " . mysqli_connect_error());
}


// Amazon S3 API credentials
$region = 'us-east-1';
$version = 'latest';
$access_key_id = $_ENV['AWS_ACCESS_KEY_ID'];
$secret_access_key = $_ENV['AWS_SECRET_ACCESS_KEY'];

$bucket = "student-applications-bucket";

// Initialize $api_error to avoid undefined variable issues
$api_error = '';
$statusMsg = '';


//get s3 ready again to upload JSON
$s3 = new S3Client([
    'version' => $version, 
    'region' => $region, 
    'credentials' => [
        'key' => $access_key_id,
        'secret' => $secret_access_key
    ]
]);



if ($_SERVER["REQUEST_METHOD"] == "POST" && isset($_POST["update_deadline"])) {

    $newDeadline = $_POST["newDeadline"];

    if (!empty($newDeadline) && strtotime($newDeadline)){

        //use prepared stmt to prevent injection
        //rewrites over first entry
        $stmt = $con->prepare("UPDATE deadlines SET date = ? WHERE id = 1");
        //adds new entries to DB
        //$stmt = $con->prepare("INSERT INTO deadlines (date) VALUES (?)");
        $stmt->bind_param("s", $newDeadline);

        if ($stmt->execute()){
            echo "<script>alert('Deadline updated successfully!');</script>";
        } else{ 
            echo "Error updating deadline: " . $stmt->error;
        }
        $stmt->close();
    }else{
        echo "<script>alert('Invalid date format');</script>";
    }
} else if ($_SERVER["REQUEST_METHOD"] == "POST" && isset($_POST["upload_renewables"])){

    $first_name = trim($_POST["first_name"]);
    $application_id = trim($_POST["application_id"]);

    //check if the use exists in db
    $stmt = $con->prepare("SELECT application_id FROM applications WHERE first_name = ? and application_id = ?");
    $stmt->bind_param("si", $first_name, $application_id);
    $stmt->execute();
    $stmt->bind_result($applicationId); //????????
    $stmt->fetch();
    $stmt->close();

    if ($applicationId){
                   //create a folder based on the applicant id
                   $folder = 'uploads/applicant_' . $applicationId . '/';

                   //EDIT: $maxFileSize = 5*1024*1024; //5MB
       
                   //loop through each file thats uploaded
                   foreach($_FILES["userfile"]["name"] as $key => $file_name){
                       //$file_name = basename($_FILES["userfile"]["name"]);
                       $file_type = pathinfo($file_name, PATHINFO_EXTENSION);
                       $allowTypes = array('pdf', 'doc', 'docx');
       
                       //check if file type is alowed
                       if (in_array($file_type, $allowTypes)) {
                           $file_temp_src = $_FILES["userfile"]["tmp_name"][$key];
       
                           if (is_uploaded_file($file_temp_src)) {
       
                           try { 
       
                               //defining s3 key which is the file path in the applicants folder
                               //$folder = 'uploads/';
                               $key = $folder . basename($file_name);
           
                               // Upload file to S3 bucket
                               $result = $s3->putObject([
                                   'Bucket' => $bucket,
                                   'Key' => $key,
                                   'SourceFile' => $file_temp_src
                               ]);
                               $result_arr = $result->toArray();
                               
                               //check to make sure file is uploaded correctly
                               if (!empty($result_arr['ObjectURL'])) {
                                   $s3_file_link = $result_arr['ObjectURL'];
                                   $status = 'success';
                                   $statusMsg = "File uploaded successfully to S3!";
                               } else {
                                   $api_error = "Upload failed! S3 object URL not found.";
                               }
                           } catch (Aws\S3\Exception\S3Exception $e) {
                               $api_error = $e->getMessage();
                           }
                       } else {
                           $statusMsg = 'Sorry, invalid file format.';
                       }
                   } else {
                       $statusMsg = "Please select a valid file to upload.";
               }
           }
    }

}





// Fetch current deadline

//most recent entry will have highest id 
//so sort in desecnding order and grab the highest id entry
$sql = "SELECT date FROM deadlines ORDER BY id DESC LIMIT 1";
$result = mysqli_query($con, $sql);

if ($result->num_rows > 0) {
    //format = Month day, year)
    $currentDeadline = (new DateTime(mysqli_fetch_assoc($result)["date"]))->format("F j, Y");
} else {
    $currentDeadline = "No deadline set"; // Default value if no data is found
}
mysqli_close($con);

?>